// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqfpzlrpqszoxbjojavc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZnB6bHJwcXN6b3hiam9qYXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3MDE2NjksImV4cCI6MjA3NTI3NzY2OX0.aEAzMZDa5Lp3p4uN51QwmjB2dYkKz9v0pLYWvUSfsVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});